#!/bin/sh

while read t n d ; do
   dn=${d:-$n}
   localPath="$(dirname $dn)"
   targetPath="$HOME/$localPath"
   name="$(basename $dn)"
   if [[ "$localPath" != "." ]]; then
      test -d "$targetPath" || mkdir -p "$targetPath"
   else
      targetPath="$HOME"
   fi
   if [[ "$t" == "l" ]]; then
      test -f "$targetPath/$n" || cp -a "$(pwd)/$n" "$targetPath/"
   else
      test -L "$targetPath/$name" || ln -sfnT "$(pwd)/$n" "$targetPath/$name"
   fi
done < make-install.list
