#!/bin/sh

while read t n ; do
   localPath="$(dirname $n)"
   targetPath="$HOME/$localPath"
   name="$(basename $n)"
   if [[ "$localPath" != "." ]]; then
      mkdir -p "$targetPath"
   else
      targetPath="$HOME"
   fi
   if [[ "$t" == "l" ]]; then
      cp -a "$(pwd)/$n" "$targetPath/"
   else
      if [[ "$t" == "d" ]]; then
         rm "$targetPath/$name"
      fi
      ln -sf "$(pwd)/$n" "$targetPath/$name"
   fi
done < make-install.list
