{
  allowUnfree = true;
  packageOverrides = pkgs: with pkgs; {
    fujitaka = pkgs.buildEnv {
      name = "fujitaka-packages";
      paths = [
        bat
        bitwarden-cli
        bottom
        calibre
        chromium
        diff-so-fancy
        dive
        docker-compose
        duc
        firefox
        font-awesome
        fzf
        gimp
        git
        gnupg
        homebank
        isync
        jq
        material-design-icons
        material-icons
        msmtp
        mupdf
        neomutt
        neovim
        nextcloud-client
        ngrok
        nix
        nodejs
        notmuch
        notmuch-addrlookup
        noto-fonts-emoji
        pass
        pavucontrol
        polybarFull
        poppler_utils
        pwgen
        restic
        rxvt-unicode
        sarasa-gothic
        scrot
        silver-searcher
        spotify
        stow
        symbola
        tdesktop
        tig
        tmux
        tree
        vagrant
        vscode
        w3m
        wireshark-qt
        xdotool
        xsel
        yarn
        yt-dlp
        zsh
      ];
    };
  };
}
